[versions]
junit = "6.0.2"


[libraries]
# com.palantir.javapoet - JavaPoet
# https://github.com/palantir/javapoet
javapoet = { module = "com.palantir.javapoet:javapoet", version = "0.9.0" }

# dev.zacsweers.kctfork - Kotlin Compile Testing
# https://github.com/ZacSweers/kotlin-compile-testing
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version = "0.12.1" }

# org.assertj - AssertJ
# https://github.com/assertj/assertj
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.6" }

# org.jetbrains:annotations - JetBrains' Annotations for JVM-based languages
# https://github.com/JetBrains/java-annotations
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }

# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# org.mockito - Mockito
# https://github.com/mockito/mockito
mockito-core = { module = "org.mockito:mockito-core", version = "5.21.0" }
